version: 0.2

# CodeBuild buildspec for Return-to-Print Backend Deployment
# This builds and deploys the Python Lambda/Chalice backend

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install chalice boto3 awscli aws-sam-cli
      - chalice --version
      - sam --version

  pre_build:
    commands:
      - echo "Pre-build phase - validating environment"
      - aws --version
      - echo "Region is $AWS_REGION"
      - echo "Account ID is $(aws sts get-caller-identity --query Account --output text)"
      - cd backend

  build:
    commands:
      - echo "Building backend application..."
      - echo "Current directory is $(pwd)"
      - ls -la
      # Option 1: If using Chalice for deployment
      - |
        if [ -f ".chalice/config.json" ]; then
          echo "Deploying with Chalice..."
          chalice deploy --stage prod --no-autogen-policy
        fi
      # Option 2: If using SAM for packaging
      - |
        if [ -f "template.yaml" ]; then
          echo "Packaging with SAM..."
          sam build
          sam package --output-template-file packaged.yaml --s3-bucket return-to-print-pipeline-artifacts-${AWS_REGION}
        fi

  post_build:
    commands:
      - echo "Post-build phase - deployment complete"
      - echo "Build completed on $(date)"
      # Output API Gateway URL if available
      - |
        if [ -f ".chalice/deployed/prod.json" ]; then
          API_URL=$(python3 -c "import json; print(json.load(open('.chalice/deployed/prod.json'))['resources'][0]['rest_api_url'])" 2>/dev/null || echo "API URL not found")
          echo "API Gateway URL: $API_URL"
        fi

artifacts:
  files:
    - '**/*'
  base-directory: backend
  name: backend-build-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - '/root/.cache/pip/**/*'

environment_variables:
  plaintext:
    DYNAMODB_TABLE: return-to-print-messages-prod
    ENVIRONMENT: prod

