AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Return-to-Print Backend Infrastructure (DynamoDB + Lambda + API Gateway)

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: Environment name
  
  TableName:
    Type: String
    Default: return-to-print-messages-prod
    Description: DynamoDB table name for messages

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11
    Architectures:
      - arm64
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref MessagesTable
        ENVIRONMENT: !Ref Environment

Resources:
  # DynamoDB Table for Messages
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: printed
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PrintedStatusIndex
          KeySchema:
            - AttributeName: printed
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: ReturnToPrint
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub return-to-print-lambda-role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt MessagesTable.Arn
                  - !Sub ${MessagesTable.Arn}/index/*
      Tags:
        - Key: Project
          Value: ReturnToPrint
        - Key: Environment
          Value: !Ref Environment

  # API Gateway REST API
  MessagePrinterApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub return-to-print-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      ThrottleSettings:
        BurstLimit: 1000
        RateLimit: 500
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
      TracingEnabled: true
      Tags:
        Project: ReturnToPrint
        Environment: !Ref Environment

  # Lambda Function Placeholder (Backend Agent will implement)
  # This is a minimal placeholder that will be replaced by Chalice deployment
  MessagePrinterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub return-to-print-api-${Environment}
      CodeUri: ../backend/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreateMessage:
          Type: Api
          Properties:
            RestApiId: !Ref MessagePrinterApi
            Path: /message
            Method: POST
        GetRecentMessages:
          Type: Api
          Properties:
            RestApiId: !Ref MessagePrinterApi
            Path: /messages/recent
            Method: GET
        GetNextToPrint:
          Type: Api
          Properties:
            RestApiId: !Ref MessagePrinterApi
            Path: /printer/next-to-print
            Method: GET
        MarkPrinted:
          Type: Api
          Properties:
            RestApiId: !Ref MessagePrinterApi
            Path: /printer/mark-printed
            Method: POST
      Tags:
        Project: ReturnToPrint
        Environment: !Ref Environment

  # CloudWatch Log Groups
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/return-to-print-api-${Environment}
      RetentionInDays: 30

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/return-to-print-api-${Environment}
      RetentionInDays: 30

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${MessagePrinterApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref MessagesTable
    Export:
      Name: !Sub ${AWS::StackName}-TableName

  DynamoDBTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt MessagesTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-TableArn

  LambdaExecutionRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaRoleArn

  ApiId:
    Description: API Gateway REST API ID
    Value: !Ref MessagePrinterApi
    Export:
      Name: !Sub ${AWS::StackName}-ApiId

